# Generated by fusen: do not edit by hand

#' Function to say hello to a given person
#'
#' @param someone Character Name of the person to say hello to
#'
#' @return Side effect: Display message in the command to say hello to someone
#' @export
#' @importFrom glue glue
#'
#' @examples
#' say_hello() # Hello You
#' say_hello(someone = "World") # Hello World
say_hello <- function(someone = "You") {
  message(glue("Hello {someone}"))
}
